#开发环境：读写分离,不分库不分表
spring:
  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/vueblog?useSSL=false&serverTimezone=Asia/Shanghai
        username: ${Japin-Config.username}
        password: ${Japin-Config.password}
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/vueblog?useSSL=false&serverTimezone=Asia/Shanghai
        username: ${Japin-Config.username}
        password: ${Japin-Config.password}
    # 读写分离配置
    masterslave:
     load-balance-algorithm-type: round_robin #轮询
    # 打开sql输出日志
    props.sql.show: true
