#测试环境配置(未引入shardingjdbc、druid)
Japin-Config:
  server_port: 8888
  username: root
  password: root
  jwt_timeout: 3000
  jmx_enabled: false #jmx监控Java程序的基本信息和运行情况
  mail_host: smtp.qq.com
  mail_user: 1940005020@qq.com
  mail_pwd: ####
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1800000

server:
  port: ${Japin-Config.server_port}

spring:
  jmx:
    enabled: ${Japin-Config.jmx_enabled}
  main:
    lazy-initialization: true  #bean懒加载
  mail:
    host:  smtp.qq.com
    username: ${Japin-Config.mail_user}
    password: ${Japin-Config.mail_pwd}
  task:
    scheduling:
      thread-name-prefix: spring_tasks_  # 调度线程名称前缀 默认 scheduling-
      shutdown:
        await-termination: false # 线程池关闭时等待所有任务完成
        await-termination-period: 10s # 调度线程关闭前最大等待时间，确保最后一定关闭
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${Japin-Config.username}
      password: ${Japin-Config.password}
      url: jdbc:mysql://localhost:3306/vueblog?serverTimezone=UTC
  redis:
    host: ${Japin-Config.redis.host}
    port: ${Japin-Config.redis.port}
    #    password:
    database: 0
  cache:
    redis:
      time-to-live: ${Japin-Config.redis.timeout} #缓冲有效时间

mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #    map-underscore-to-camel-case: true #默认就是true
  #    config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    db-config:
      table-prefix: zb_   #表名映射
      logic-delete-value: 1  #逻辑删除是
      logic-not-delete-value: 0 #逻辑删除否

jwt:
  configuration:
    expire: ${Japin-Config.jwt_timeout}
    secret: user

blog:
  swagger:
    enabled: true #是否启用swagger
    docket:
      user:
        title: 模块
        base-package: com.Blog.controller
