#读写分离，分表不分库
Japin-Config:
  server_port: 8081
  username: root
  password: root
  jwt_timeout: 3000
  jmx_enabled: false #jmx监控Java程序的基本信息和运行情况
  mail_host: smtp.qq.com
  mail_user: 1940005020@qq.com
  mail_pwd: xaipiakcatobehbe
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1800000

server:
  port: ${Japin-Config.server_port}

spring:
  jmx:
    enabled: ${Japin-Config.jmx_enabled}
  main:
    lazy-initialization: true  #bean懒加载
    allow-bean-definition-overriding: true
  mail:
    host: smtp.qq.com
    username: ${Japin-Config.mail_user}
    password: ${Japin-Config.mail_pwd}
  task:
    scheduling:
      thread-name-prefix: spring_tasks_  # 调度线程名称前缀 默认 scheduling-
      shutdown:
        await-termination: false # 线程池关闭时等待所有任务完成
        await-termination-period: 10s # 调度线程关闭前最大等待时间，确保最后一定关闭
  #配置数据源，给数据源起名user0,user1...此处可配置多数据源
  shardingsphere.datasource.names: master,slave
  # 数据源
  shardingsphere.datasource.master.type: com.alibaba.druid.pool.DruidDataSource
  shardingsphere.datasource.master.driver-class-name: com.mysql.cj.jdbc.Driver
  shardingsphere.datasource.master.url: jdbc:mysql://localhost:3306/blog_db?characterEncoding=utf-8
  shardingsphere.datasource.master.username: root
  shardingsphere.datasource.master.password: root

  shardingsphere.datasource.slave.type: com.alibaba.druid.pool.DruidDataSource
  shardingsphere.datasource.slave.driver-class-name: com.mysql.cj.jdbc.Driver
  shardingsphere.datasource.slave.url: jdbc:mysql://localhost:3306/blog_db?characterEncoding=utf-8
  shardingsphere.datasource.slave.username: root
  shardingsphere.datasource.slave.password: root

  # 配置表的分布，表的策略
  shardingsphere.sharding.tables.blog.actual-data-nodes: ds0.blog${0..2}
  # inline表达式   指定分片策略 约定id值
  shardingsphere.sharding.tables.blog.table-strategy.inline.sharding-column: id
  shardingsphere.sharding.tables.blog.table-strategy.inline.algorithm-expression: blog${id.longValue() % 3}

  # 读写分离配置   ds0为临时数据源命名
  shardingsphere.sharding.master-slave-rules.ds0.master-data-source-name: master
  shardingsphere.sharding.master-slave-rules.ds0.slave-data-source-names: slave
  # 打开sql输出日志
  shardingsphere.props.sql.show: true

  redis:
    host: ${Japin-Config.redis.host}
    port: ${Japin-Config.redis.port}
    #    password:
    database: 0
  cache:
    redis:
      time-to-live: ${Japin-Config.redis.timeout} #缓冲有效时间

mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #    map-underscore-to-camel-case: true #默认就是true
  #    config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    db-config:
#      table-prefix: zb_   #表名映射
      logic-delete-value: 1  #逻辑删除是
      logic-not-delete-value: 0 #逻辑删除否

jwt:
  configuration:
    expire: ${Japin-Config.jwt_timeout}
    secret: user

blog:
  swagger:
    enabled: true #是否启用swagger
    docket:
      user:
        title: 模块
        base-package: com.Blog.controller
